#!/usr/bin/env bash
# trello.sh — direct Trello REST dispatcher generated by un-mcp.
# Replaces the mcp-server-trello MCP with plain curl. Costs nothing in context until run.
# Usage: ./trello.sh <command> [args...]
set -euo pipefail

# --- config -----------------------------------------------------------------
BASE="https://api.trello.com/1"
# Load env from project root .env, then skill-local .env (local overrides root),
# without echoing secrets. Project root resolved via git, else 4 levels up.
_dir="$(cd "$(dirname "$0")" && pwd)"
_root="$(git -C "$_dir" rev-parse --show-toplevel 2>/dev/null || echo "$_dir/../../../..")"
for _envf in "$_root/.env" "$_dir/../.env"; do
  if [[ -f "$_envf" ]]; then
    set -a; # shellcheck disable=SC1091
    . "$_envf"; set +a
  fi
done

# --- credential guard -------------------------------------------------------
require() {
  local missing=0
  for var in "$@"; do
    if [[ -z "${!var:-}" ]]; then
      echo "Missing env var: $var (see SETUP.md)" >&2
      missing=1
    fi
  done
  [[ $missing -eq 0 ]] || exit 1
}

# Resolve a board id: explicit arg > TRELLO_BOARD_ID env. Mirrors the MCP's "active board".
board_or_default() {
  local b="${1:-${TRELLO_BOARD_ID:-}}"
  if [[ -z "$b" ]]; then
    echo "No boardId given and TRELLO_BOARD_ID is unset (see SETUP.md)" >&2
    exit 1
  fi
  printf '%s' "$b"
}

# --- helpers ----------------------------------------------------------------
# call METHOD PATH [extra-query] [curl-args...] — body to stdout, "HTTP:<code>" to
# stderr. Keeping status off stdout is what lets the body pipe cleanly into the
# summariser; emitting the status inline would corrupt the JSON on the last line.
# extra-query is merged with the key+token auth (no leading ? / &). The full URL
# (which carries the secret token) is passed to curl via a stdin config (-K -),
# NOT argv, so the token never shows up in `ps` output or shell history.
call() {
  local method="$1" path="$2" extra="${3:-}"; shift 3 || shift $#
  local q="key=${TRELLO_API_KEY}&token=${TRELLO_TOKEN}"
  [[ -n "$extra" ]] && q="$extra&$q"
  local resp code
  resp="$(curl -g -sS -X "$method" -w $'\n%{http_code}' "$@" -K - <<CFG
url = "$BASE$path?$q"
CFG
)"
  code="${resp##*$'\n'}"          # trailing line = status
  local body="${resp%$'\n'*}"     # everything before it = body
  # On HTTP >=400, send body+status to stderr and return non-zero so the failure
  # is catchable by exit code and pretty() never reshapes an error object into a
  # misleading result (e.g. projecting {id,name} off {"message":"..."}).
  if [[ "$code" =~ ^[0-9]+$ ]] && ((code >= 400)); then
    printf '%s\n' "$body" >&2
    printf 'HTTP:%s\n' "$code" >&2
    return 1
  fi
  printf '%s\n' "$body"           # newline-terminated so raw non-pretty output
                                  # ends cleanly; pretty() strips it via $(cat).
  printf 'HTTP:%s\n' "$code" >&2
}

# urlencode a single value for safe query use. Pure-bash percent-encoder — needs
# no external tool, so it works on any OS with just bash. LC_ALL=C makes
# ${#s}/${s:i:1} iterate BYTES, so each byte of a multibyte UTF-8 char is encoded
# on its own (encoding a char by its first byte only would corrupt it).
enc() {
  local LC_ALL=C s="$1" i c n out=""
  for ((i = 0; i < ${#s}; i++)); do
    c="${s:i:1}"
    case "$c" in
      [a-zA-Z0-9.~_-]) out+="$c" ;;
      # "'$c" yields the byte value; high bytes come out sign-extended (negative),
      # so mask to 0..255 before formatting as %XX.
      *) printf -v n '%d' "'$c"; printf -v c '%%%02X' "$(( n & 0xff ))"; out+="$c" ;;
    esac
  done
  printf '%s' "$out"
}

# enc_query "k1=v1&k2=v2" — urlencode the VALUE side of each key=value pair,
# leaving keys and & / = structure intact. Lets raw <query> args contain spaces.
# Pass plain values (not pre-encoded) or %XX will be double-encoded.
enc_query() {
  local out="" pair k v
  # read -ra splits on IFS without glob-expanding, unlike `for pair in $1`
  # (an unquoted value like name=* would otherwise expand against the cwd).
  local -a pairs; IFS='&' read -ra pairs <<< "$1"
  for pair in "${pairs[@]}"; do
    [[ -z "$pair" ]] && continue
    if [[ "$pair" == *=* ]]; then
      k="${pair%%=*}"; v="${pair#*=}"; out+="&$k=$(enc "$v")"
    else
      out+="&$pair"
    fi
  done
  printf '%s' "${out#&}"
}

# pretty JSFILTER — summarise via node. JSFILTER is a JS arrow fn (parsed JSON in,
# value out); node runs cross-platform (Windows/macOS/Linux) and is the usual
# agent runtime, so it needs no OS-specific install. Buffers stdin first: if node
# is missing OR the body isn't JSON (error page, plain text), the RAW body is
# printed so nothing is ever silently dropped. Empty body prints nothing.
pretty() {
  local body; body="$(cat)"
  [[ -z "$body" ]] && return
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$body" | node -e '
let s = "";
process.stdin.setEncoding("utf8");   // decode as UTF-8 so a multibyte char split
                                     // across chunks is not corrupted (s += Buffer would)
process.stdin.on("data", d => s += d).on("end", () => {
  try {
    const j = JSON.parse(s);
    const out = (0, eval)(process.argv[1])(j);   // JSFILTER is trusted (script-defined), never user input
    console.log(typeof out === "string" ? out : JSON.stringify(out, null, 2));
  } catch (e) {
    process.stdout.write(s.endsWith("\n") ? s : s + "\n");   // not JSON / filter failed → raw
  }
});' "$1"
  else
    printf '%s\n' "$body"
  fi
}

# --- commands ---------------------------------------------------------------
cmd="${1:-help}"; shift || true
# Every command except help needs credentials — check once here (was per-branch).
[[ "$cmd" =~ ^(help|-h|--help)$ ]] || require TRELLO_API_KEY TRELLO_TOKEN
# node powers response summarisation (parsing + projecting the JSON). Without it
# the script still works but returns RAW bodies, so warn once (not for help)
# rather than degrade silently. node is cross-platform and usually already present.
[[ "$cmd" =~ ^(help|-h|--help)$ ]] || command -v node >/dev/null 2>&1 || \
  echo "note: node not found — responses are NOT summarised, raw payloads returned (install Node.js)" >&2
case "$cmd" in
  # ---- Boards -------------------------------------------------------------
  list-boards)  # MCP: list_boards
    call GET "/members/me/boards" "fields=id,name,url,closed" | pretty 'j=>j'
    ;;

  board-info)  # MCP: get_active_board_info
    b="$(board_or_default "${1:-}")"
    call GET "/boards/$b" "fields=id,name,desc,url,closed,idOrganization" | pretty 'j=>j'
    ;;

  list-workspaces)  # MCP: list_workspaces
    call GET "/members/me/organizations" "fields=id,displayName,name,url" | pretty 'j=>j'
    ;;

  boards-in-workspace)  # MCP: list_boards_in_workspace
    ws="${1:?usage: boards-in-workspace <workspaceId>}"
    call GET "/organizations/$ws/boards" "fields=id,name,url,closed" | pretty 'j=>j'
    ;;

  # ---- Lists --------------------------------------------------------------
  get-lists)  # MCP: get_lists
    b="$(board_or_default "${1:-}")"
    call GET "/boards/$b/lists" "fields=id,name,pos,closed" | pretty 'j=>j'
    ;;

  add-list)  # MCP: add_list_to_board (write)
    name="${1:?usage: add-list \"<name>\" [boardId]}"
    b="$(board_or_default "${2:-}")"
    echo "About to create list \"$name\" on board $b" >&2
    call POST "/lists" "name=$(enc "$name")&idBoard=$b" | pretty 'j=>({id:j.id,name:j.name})'
    ;;

  archive-list)  # MCP: archive_list (write)
    id="${1:?usage: archive-list <listId>}"
    echo "About to archive list $id" >&2
    call PUT "/lists/$id/closed" "value=true" | pretty 'j=>({id:j.id,name:j.name,closed:j.closed})'
    ;;

  update-list)  # MCP: update_list / update_list_position. Pass raw query, e.g. name=Foo or pos=top
    id="${1:?usage: update-list <listId> <query> (e.g. name=Foo  |  pos=top  |  closed=true)}"
    q="${2:?usage: update-list <listId> <query>}"
    echo "About to update list $id ($q)" >&2
    call PUT "/lists/$id" "$(enc_query "$q")" | pretty 'j=>({id:j.id,name:j.name,pos:j.pos,closed:j.closed})'
    ;;

  # ---- Cards --------------------------------------------------------------
  get-card)  # MCP: get_card
    id="${1:?usage: get-card <cardId>}"
    call GET "/cards/$id" "fields=id,name,desc,due,start,dueComplete,idList,labels,url&customFieldItems=true" | pretty 'j=>j'
    ;;

  cards-in-list)  # MCP: get_cards_by_list_id
    listId="${1:?usage: cards-in-list <listId>}"
    call GET "/lists/$listId/cards" "fields=id,name,desc,due,idList,url" | pretty 'j=>j'
    ;;

  my-cards)  # MCP: get_my_cards
    call GET "/members/me/cards" "fields=id,name,due,idBoard,idList,url" | pretty 'j=>j'
    ;;

  add-card)  # MCP: add_card_to_list (write)
    listId="${1:?usage: add-card <listId> \"<name>\" [\"<desc>\"]}"
    name="${2:?usage: add-card <listId> \"<name>\" [\"<desc>\"]}"
    desc="${3:-}"
    echo "About to create card \"$name\" in list $listId" >&2
    call POST "/cards" "idList=$listId&name=$(enc "$name")&desc=$(enc "$desc")" | pretty 'j=>({id:j.id,name:j.name,url:j.url})'
    ;;

  update-card)  # MCP: update_card_details. Pass raw query, e.g. name=New&desc=...&due=2026-08-01T12:00:00Z
    id="${1:?usage: update-card <cardId> <query> (e.g. name=New  |  dueComplete=true  |  desc=...)}"
    q="${2:?usage: update-card <cardId> <query>}"
    echo "About to update card $id ($q)" >&2
    call PUT "/cards/$id" "$(enc_query "$q")" | pretty 'j=>({id:j.id,name:j.name,due:j.due,dueComplete:j.dueComplete})'
    ;;

  move-card)  # MCP: move_card (write)
    id="${1:?usage: move-card <cardId> <listId>}"
    listId="${2:?usage: move-card <cardId> <listId>}"
    echo "About to move card $id to list $listId" >&2
    call PUT "/cards/$id" "idList=$listId" | pretty 'j=>({id:j.id,name:j.name,idList:j.idList})'
    ;;

  archive-card)  # MCP: archive_card (write)
    id="${1:?usage: archive-card <cardId>}"
    echo "About to archive card $id" >&2
    call PUT "/cards/$id/closed" "value=true" | pretty 'j=>({id:j.id,name:j.name,closed:j.closed})'
    ;;

  # ---- Comments -----------------------------------------------------------
  card-comments)  # MCP: get_card_comments
    id="${1:?usage: card-comments <cardId> [limit]}"
    limit="${2:-100}"
    call GET "/cards/$id/actions" "filter=commentCard&limit=$limit" \
      | pretty 'j=>j.map(a=>({id:a.id,date:a.date,by:a.memberCreator&&a.memberCreator.fullName,text:a.data&&a.data.text}))'
    ;;

  add-comment)  # MCP: add_comment (write)
    id="${1:?usage: add-comment <cardId> \"<text>\"}"
    text="${2:?usage: add-comment <cardId> \"<text>\"}"
    echo "About to comment on card $id" >&2
    call POST "/cards/$id/actions/comments" "text=$(enc "$text")" | pretty 'j=>({id:j.id,text:j.data&&j.data.text})'
    ;;

  update-comment)  # MCP: update_comment (write)
    id="${1:?usage: update-comment <commentId> \"<text>\"}"
    text="${2:?usage: update-comment <commentId> \"<text>\"}"
    echo "About to edit comment $id" >&2
    call PUT "/actions/$id" "text=$(enc "$text")" | pretty 'j=>({id:j.id,text:j.data&&j.data.text})'
    ;;

  delete-comment)  # MCP: delete_comment (destructive)
    id="${1:?usage: delete-comment <commentId>}"
    echo "About to DELETE comment $id — irreversible" >&2
    call DELETE "/actions/$id"
    ;;

  # ---- Checklists ---------------------------------------------------------
  board-checklists)  # backs get_checklist_items / get_checklist_by_name (fetch, then filter by name)
    b="$(board_or_default "${1:-}")"
    call GET "/boards/$b/checklists" "checkItems=all&fields=id,name" \
      | pretty 'j=>j.map(c=>({id:c.id,name:c.name,items:(c.checkItems||[]).map(i=>({id:i.id,name:i.name,state:i.state}))}))'
    ;;

  card-checklists)  # checklists on a single card (needed to get checklist ids for add-checklist-item)
    id="${1:?usage: card-checklists <cardId>}"
    call GET "/cards/$id/checklists" "checkItems=all" \
      | pretty 'j=>j.map(c=>({id:c.id,name:c.name,items:(c.checkItems||[]).map(i=>({id:i.id,name:i.name,state:i.state}))}))'
    ;;

  add-checklist-item)  # MCP: add_checklist_item (write). Needs the checklist id (from card-checklists)
    checklistId="${1:?usage: add-checklist-item <checklistId> \"<text>\"}"
    text="${2:?usage: add-checklist-item <checklistId> \"<text>\"}"
    echo "About to add item to checklist $checklistId" >&2
    call POST "/checklists/$checklistId/checkItems" "name=$(enc "$text")" | pretty 'j=>({id:j.id,name:j.name,state:j.state})'
    ;;

  update-checklist-item)  # MCP: update_checklist_item (write). query e.g. state=complete or name=Foo
    cardId="${1:?usage: update-checklist-item <cardId> <checkItemId> <query> (e.g. state=complete)}"
    itemId="${2:?usage: update-checklist-item <cardId> <checkItemId> <query>}"
    q="${3:?usage: update-checklist-item <cardId> <checkItemId> <query>}"
    echo "About to update check item $itemId on card $cardId ($q)" >&2
    call PUT "/cards/$cardId/checkItem/$itemId" "$(enc_query "$q")" | pretty 'j=>({id:j.id,name:j.name,state:j.state})'
    ;;

  delete-checklist-item)  # MCP: delete_checklist_item (destructive)
    cardId="${1:?usage: delete-checklist-item <cardId> <checkItemId>}"
    itemId="${2:?usage: delete-checklist-item <cardId> <checkItemId>}"
    echo "About to DELETE check item $itemId on card $cardId — irreversible" >&2
    call DELETE "/cards/$cardId/checkItem/$itemId"
    ;;

  # ---- Attachments --------------------------------------------------------
  attach-url)  # MCP: attach_image_to_card / attach_file_to_card (write; both are POST url attachments)
    id="${1:?usage: attach-url <cardId> <url> [\"<name>\"]}"
    url="${2:?usage: attach-url <cardId> <url> [\"<name>\"]}"
    name="${3:-}"
    echo "About to attach $url to card $id" >&2
    call POST "/cards/$id/attachments" "url=$(enc "$url")&name=$(enc "$name")" | pretty 'j=>({id:j.id,name:j.name,url:j.url})'
    ;;

  # ---- Custom fields ------------------------------------------------------
  board-custom-fields)  # MCP: get_board_custom_fields
    b="$(board_or_default "${1:-}")"
    call GET "/boards/$b/customFields" | pretty 'j=>j.map(f=>({id:f.id,name:f.name,type:f.type,options:(f.options||[]).map(o=>o.value&&o.value.text)}))'
    ;;

  # ---- Activity -----------------------------------------------------------
  recent-activity)  # MCP: get_recent_activity
    b="$(board_or_default "${1:-}")"
    limit="${2:-10}"
    call GET "/boards/$b/actions" "limit=$limit" \
      | pretty 'j=>j.map(a=>({id:a.id,type:a.type,date:a.date,by:a.memberCreator&&a.memberCreator.fullName}))'
    ;;

  help|-h|--help)
    # List every case arm. The trailing "\)" is essential: it is what tells a
    # case label ("  list-boards)") apart from a 2-space-indented statement inside
    # a function ("  local x", "  if ...", "  for ...") — without it the list fills
    # with shell keywords. sed strips the indent and everything from ")" on (so a
    # trailing "# comment" is dropped too). Whole-line match, no -o, for portability
    # across BSD grep and ugrep.
    grep -E '^  [a-z][a-z|-]*\)' "$0" | sed -E 's/^  //; s/\).*//'
    ;;

  *)
    echo "Unknown command: $cmd" >&2
    echo "Run: $0 help" >&2
    exit 1
    ;;
esac
