#!/usr/bin/env bash
# <service>.sh — direct REST dispatcher generated by un-mcp.
# Replaces the <service> MCP with plain curl. Costs nothing in context until run.
# Usage: ./<service>.sh <command> [args...]
set -euo pipefail

# --- config -----------------------------------------------------------------
BASE="https://api.<service>.com"   # set the real base URL
# Load env from project root .env, then skill-local .env (local overrides root),
# without echoing secrets. Project root resolved via git, else 4 levels up.
_dir="$(cd "$(dirname "$0")" && pwd)"
_root="$(git -C "$_dir" rev-parse --show-toplevel 2>/dev/null || echo "$_dir/../../../..")"
for _envf in "$_root/.env" "$_dir/../.env"; do
  if [[ -f "$_envf" ]]; then
    set -a; # shellcheck disable=SC1091
    . "$_envf"; set +a
  fi
done

# --- credential guard -------------------------------------------------------
require() {
  local missing=0
  for var in "$@"; do
    if [[ -z "${!var:-}" ]]; then
      echo "Missing env var: $var (see SETUP.md)" >&2
      missing=1
    fi
  done
  [[ $missing -eq 0 ]] || exit 1
}

# --- helpers ----------------------------------------------------------------
# call METHOD PATH [curl-args...] — body to stdout, "HTTP:<code>" to stderr.
# Keeping status off stdout is what lets the body pipe cleanly into the summariser;
# emitting it inline would corrupt the JSON on the trailing line.
#
# The URL and the auth secret are passed to curl via a stdin config (-K -), NOT
# argv, so the token never shows up in `ps` output or shell history. Pick the
# auth line for your service and delete the others (see references/rest-mapping.md):
#   Bearer:  header = "Authorization: Bearer TOKEN"   (Linear: no "Bearer" prefix)
#   Basic:   user   = "EMAIL:API_TOKEN"
#   Query:   append ?key=KEY&token=TOKEN to the url line (Trello) — no header
# Only ONE auth line goes in the heredoc; the heredoc expands shell vars, so a
# reference to an unset var there would trip `set -u`. Keep unused patterns as
# these shell comments, not as curl-comment lines inside the heredoc.
call() {
  local method="$1" path="$2"; shift 2
  local resp code
  resp="$(curl -g -sS -X "$method" -w $'\n%{http_code}' "$@" -K - <<CFG
url = "$BASE$path"
header = "Authorization: Bearer ${<SERVICE>_TOKEN}"
CFG
)"
  code="${resp##*$'\n'}"          # trailing line = status
  local body="${resp%$'\n'*}"     # everything before it = body
  # On HTTP >=400, send body+status to stderr and return non-zero so the failure
  # is catchable by exit code and pretty() never reshapes an error object into a
  # misleading result (e.g. projecting {id,name} off {"message":"..."}).
  if [[ "$code" =~ ^[0-9]+$ ]] && ((code >= 400)); then
    printf '%s\n' "$body" >&2
    printf 'HTTP:%s\n' "$code" >&2
    return 1
  fi
  printf '%s\n' "$body"           # newline-terminated; pretty() strips it via $(cat)
  printf 'HTTP:%s\n' "$code" >&2
}

# pretty JSFILTER — summarise via node. JSFILTER is a JS arrow fn (parsed JSON in,
# value out); node runs cross-platform (Windows/macOS/Linux) and is the usual
# agent runtime, so it needs no OS-specific install. Buffers stdin first: if node
# is missing OR the body isn't JSON (error page, plain text), the RAW body is
# printed so nothing is ever silently dropped. Empty body prints nothing.
pretty() {
  local body; body="$(cat)"
  [[ -z "$body" ]] && return
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$body" | node -e '
let s = "";
process.stdin.setEncoding("utf8");   // decode as UTF-8 so a multibyte char split
                                     // across chunks is not corrupted (s += Buffer would)
process.stdin.on("data", d => s += d).on("end", () => {
  try {
    const j = JSON.parse(s);
    const out = (0, eval)(process.argv[1])(j);   // JSFILTER is trusted (script-defined), never user input
    console.log(typeof out === "string" ? out : JSON.stringify(out, null, 2));
  } catch (e) {
    process.stdout.write(s.endsWith("\n") ? s : s + "\n");   // not JSON / filter failed → raw
  }
});' "$1"
  else
    printf '%s\n' "$body"
  fi
}

# --- commands ---------------------------------------------------------------
cmd="${1:-help}"; shift || true
# Every command except help needs credentials — check once up front.
[[ "$cmd" =~ ^(help|-h|--help)$ ]] || require <SERVICE>_TOKEN
# node powers response summarisation (parsing + projecting the JSON). Without it
# the script still works but returns RAW bodies, so warn once (not for help)
# rather than degrade silently. node is cross-platform and usually already present.
[[ "$cmd" =~ ^(help|-h|--help)$ ]] || command -v node >/dev/null 2>&1 || \
  echo "note: node not found — responses are NOT summarised, raw payloads returned (install Node.js)" >&2
case "$cmd" in
  # Each read pipes into pretty 'JSFILTER', a JS arrow fn that trims the payload:
  #   whole body ......... 'j=>j'
  #   array projection ... 'j=>j.map(x=>({id:x.id,name:x.name}))'
  #   object projection .. 'j=>({id:j.id,name:j.name})'
  list-things)
    call GET "/things" | pretty 'j=>j.map(x=>({id:x.id,name:x.name}))'
    ;;

  things-in-parent)
    parent="${1:?usage: things-in-parent <parentId>}"
    call GET "/parents/$parent/things" | pretty 'j=>j.map(x=>({id:x.id,name:x.name}))'
    ;;

  get-thing)
    id="${1:?usage: get-thing <id>}"
    call GET "/things/$id" | pretty 'j=>j'
    ;;

  create-thing)
    # WRITE — mutates remote data. Keep explicit; never the default arm.
    parent="${1:?usage: create-thing <parentId> \"<name>\"}"
    name="${2:?usage: create-thing <parentId> \"<name>\"}"
    echo "About to create thing \"$name\" in $parent" >&2
    # Build the JSON body with node so quotes/backslashes/newlines in $name can't
    # break out of the string or inject fields. Never hand-concatenate JSON.
    # (Form-encoded APIs like Trello instead url-encode each value with a pure-bash
    # percent-encoder — see the generated trello skill for that pattern.)
    body="$(node -e 'process.stdout.write(JSON.stringify({parentId:process.argv[1], name:process.argv[2]}))' "$parent" "$name")"
    call POST "/things" -H "Content-Type: application/json" -d "$body" | pretty 'j=>j'
    ;;

  help|-h|--help)
    # List every case arm. The trailing "\)" is essential: it distinguishes a case
    # label ("  list-things)") from a 2-space-indented statement inside a function
    # ("  local x", "  if ...") — drop it and the list fills with shell keywords.
    # sed strips the indent and everything from ")" on (so trailing "# comments" go
    # too). Whole-line match, no -o, for portability across BSD grep and ugrep.
    grep -E '^  [a-z][a-z|-]*\)' "$0" | sed -E 's/^  //; s/\).*//'
    ;;

  *)
    echo "Unknown command: $cmd" >&2
    echo "Run: $0 help" >&2
    exit 1
    ;;
esac
